import type { Metadata } from 'next'
import '@/assets/styles/globals.css'
import Header from '@/widgets/header/Header'

export const metadata: Metadata = {
	title: 'Behoof - Лучшие цены в интернет-магазинах ',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	)
}
